server:
  port: 8071
spring:
  application:
    name: "configserver"
  profiles:
    # active: native
    active: git
  cloud:
    config:
      server:
        # native:
        # search-locations: "classpath:/config"
        # search-locations: "file:///Users//eazybytes//Documents//config"
        git:
          uri: "https://github.com/tranphuocloc070699/smosky-config-repo.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
